module.exports = {
  weapon_assault_rifle: {
    iw8_ar_kilo433: "Kilo 141",
    iw8_ar_falima: "FAL",
    iw8_ar_mike4: "M4A1",
    iw8_ar_falpha: "FAMAS",
    iw8_ar_asierra12: "Oden",
    iw8_ar_mcharlie: "M13",
    iw8_ar_scharlie: "FN SCAR 17S",
    iw8_ar_akilo47: "AK-47 ",
    iw8_ar_tango21: "RAM-7",
    iw8_ar_sierra552: "GRAU 5.56",
  },
  weapon_smg: {
    iw8_sm_mpapa7: "MP7",
    iw8_sm_augolf: "AUG",
    iw8_sm_papa90: "P90",
    iw8_sm_mpapa5: "MP5",
    iw8_sm_smgolf45: "Striker 45",
    iw8_sm_beta: "Bizon",
    iw8_sm_uzulu: "Uzulu",
  },
  weapon_shotgun: {
    iw8_sh_charlie725: "725",
    iw8_sh_oscar12: "Origin 12",
    iw8_sh_romeo870: "Model 680",
    iw8_sh_dpapa12: "R9 0",
  },
  weapon_marksman: {
    iw8_sn_sbeta: "HDR",
    iw8_sn_kilo98: "KAR98K",
    iw8_sn_mike14: "EBR-14",
    iw8_sn_sksierra: "SKS",
  },
  weapon_lmg: {
    iw8_lm_kilo121: "M91",
    iw8_lm_mgolf34: "Holger-26",
    iw8_lm_lima86: "SA87",
    iw8_lm_pkilo: "PKM",
    iw8_lm_mgolf36: "MG34",
  },
  weapon_sniper: {
    iw8_sn_alpha50: "AX-50",
    iw8_sn_hdromeo: "Dragunov",
    iw8_sn_delta: "MK2 Carbine",
  },
  weapon_launcher: {
    iw8_la_rpapa7: "RPG-7",
    iw8_la_gromeo: "PILA",
    iw8_la_juliet: "JOKR",
    iw8_la_kgolf: "Strela-p",
  },
  weapon_pistol: {
    iw8_pi_cpapa: ".357 Magnum",
    iw8_pi_mike9: "Renetti",
    iw8_pi_mike1911: "M1911",
    iw8_pi_golf21: "X16",
    iw8_pi_decho: ".50 GS",
    iw8_pi_papa320: "M19",
  },
  lethals: {
    equip_frag: "Frag Grenade",
    equip_thermite: "Thermite Grenade",
    equip_semtex: "Semtex",
    equip_claymore: "Claymore Mine",
    equip_c4: "C4",
    equip_at_mine: "Anti Tank Mine",
    equip_throwing_knife: "Throwing Knife",
    equip_molotov: "Molotov",
  },
  tacticals: {
    equip_gas_grenade: "Gas Grenade",
    equip_snapshot_grenade: "Snapshot Grenade",
    equip_decoy: "Decoy",
    equip_smoke: "Smoke",
    equip_concussion: "Concussion Grenade",
    equip_hb_sensor: "Heartbeat Sensor",
    equip_flash: "Flashbang",
    equip_adrenaline: "Stim",
  },
  weapon_other: {
    iw8_me_riotshield: "Riot Shield",
  },
  weapon_melee: {
    iw8_knife: "Knife",
  },
};
